# Here, you can upgrade your layouts and views to AssetHat. For example, find
# this sort of code in your app:
#
#     stylesheet_link_tag 'reset', 'application'
#     javascript_include_tag(
#       Rails.env.production? ? '<Google CDN URL>' : 'jquery-1.6.1')
#     javascript_include_tag 'utilities', 'application'
#
# Create matching bundles in this file (no `.css` or `.js` suffixes needed;
# ERb is supported if you need it):
#
#     css:
#       bundles:
#         application:
#           - reset
#           - application
#     js:
#       vendors:
#         jquery:
#           version: 1.6.1
#       bundles:
#         application:
#           - utilities
#           - application
#
# Then, simplify your layouts and views to match your bundles:
#
#     include_css :bundle => 'application'
#     include_js  :jquery, :bundle => 'application'
#
# This makes it really easy to reuse sets of CSS/JS files across layouts.
#
# Lastly, set up your deployment script to run `rake asset_hat:minify`
# automatically. This creates minified versions of your CSS/JS; your original
# code is untouched. If you deploy with Capistrano, here's an example recipe:
# https://github.com/mintdigital/asset_hat/blob/master/lib/asset_hat/capistrano.rb
#
# That's it! In development, individual CSS/JS files are loaded separately,
# and your local copy of jQuery is used. In production, your minified CSS/JS
# bundles are loaded, and jQuery is loaded from Google's CDN.
#
# More info: https://github.com/mintdigital/asset_hat/#readme

css:
  engine: cssmin
  # Available minification engines:
  # http://mintdigital.github.com/asset_hat/doc/classes/AssetHat/CSS/Engines.html

  bundles:
    application: []

js:
  engine: jsmin
  # Available minification engines:
  # http://mintdigital.github.com/asset_hat/doc/classes/AssetHat/JS/Engines.html

  # Enable if you're using jQuery or other popular JS:
  #
  # vendors:
  #   jquery:
  #     version: 1.6.1
  #
  # Supported vendors:
  # http://mintdigital.github.com/asset_hat/doc/classes/AssetHat/JS/Vendors.html

  bundles:
    application: []
      
      
      
#<link href="/assets/application.css?body=1" media="all" rel="stylesheet" type="text/css" />
#<link href="/assets/jquery.ui.core.css?body=1" media="all" rel="stylesheet" type="text/css" />
#<link href="/assets/jquery.ui.theme.css?body=1" media="all" rel="stylesheet" type="text/css" />
#<link href="/assets/dataTables/src/demo_table_jui.css?body=1" media="all" rel="stylesheet" type="text/css" />
#<link href="/assets/easyui/default/easyui.css?body=1" media="all" rel="stylesheet" type="text/css" />
#<link href="/assets/easyui/icon.css?body=1" media="all" rel="stylesheet" type="text/css" />
#<link href="/assets/jquery.fancybox.css?body=1" media="all" rel="stylesheet" type="text/css" />
#<link href="/assets/kendo.blueopal.min.css?body=1" media="all" rel="stylesheet" type="text/css" />
#<link href="/assets/kendo.common.min.css?body=1" media="all" rel="stylesheet" type="text/css" />  

#<script src="/assets/jquery.js?body=1" type="text/javascript"></script>
#<script src="/assets/jquery_ujs.js?body=1" type="text/javascript"></script>
#<script src="/assets/jquery-ui.js?body=1" type="text/javascript"></script>
#<script src="/assets/date.js?body=1" type="text/javascript"></script>
#<script src="/assets/jquery.chromatable.js?body=1" type="text/javascript"></script>
#<script src="/assets/jquery.easyui.min.js?body=1" type="text/javascript"></script>
#<script src="/assets/jquery.fancybox.pack.js?body=1" type="text/javascript"></script>
#<script src="/assets/jquery.forcenumeric.js?body=1" type="text/javascript"></script>
#<script src="/assets/jquery.functions.js?body=1" type="text/javascript"></script>
#<script src="/assets/jquery.placeholder.js?body=1" type="text/javascript"></script>
#<script src="/assets/kendo.web.min.js?body=1" type="text/javascript"></script>
#<script src="/assets/dataTables/jquery.dataTables.js?body=1" type="text/javascript"></script>
#<script src="/assets/turbolinks.js?body=1" type="text/javascript"></script>
#<script src="/assets/application.js?body=1" type="text/javascript"></script>